spring.application.name=payment_intergration_sys_backend


spring.datasource.url=jdbc:mysql://localhost:3306/payment_inter_sys?useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true
spring.datasource.username=root
spring.datasource.password=flexx123$5678*
server.port=1020

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql = true
spring.main.allow-circular-references = true

jwt.secret = UtMAYByAOOUaythfK2QofJFKomJxYArXOF6yQrPm5pk=

logging.level.root=INFO
logging.level.org.springframework.security=DEBUG
logging.level.com.techsensei.payment_intergration_system=DEBUG

spring.data.redis.host=localhost
spring.data.redis.port=6379

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
